// Code generated by mockery v2.53.6. DO NOT EDIT.

package repository

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockEmail is an autogenerated mock type for the Email type
type MockEmail struct {
	mock.Mock
}

// CleanupExpired provides a mock function with given fields: ctx
func (_m *MockEmail) CleanupExpired(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CleanupExpired")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateOrUpdate provides a mock function with given fields: ctx, userID, ttl
func (_m *MockEmail) CreateOrUpdate(ctx context.Context, userID uuid.UUID, ttl time.Duration) (uuid.UUID, error) {
	ret := _m.Called(ctx, userID, ttl)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrUpdate")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Duration) (uuid.UUID, error)); ok {
		return rf(ctx, userID, ttl)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Duration) uuid.UUID); ok {
		r0 = rf(ctx, userID, ttl)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Duration) error); ok {
		r1 = rf(ctx, userID, ttl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VerifyAndConsume provides a mock function with given fields: ctx, token
func (_m *MockEmail) VerifyAndConsume(ctx context.Context, token uuid.UUID) (uuid.UUID, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for VerifyAndConsume")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (uuid.UUID, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) uuid.UUID); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockEmail creates a new instance of MockEmail. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmail(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmail {
	mock := &MockEmail{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
