// Code generated by mockery v2.53.6. DO NOT EDIT.

package service

import (
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// MockEmailVerifier is an autogenerated mock type for the EmailVerifier type
type MockEmailVerifier struct {
	mock.Mock
}

// SendVerification provides a mock function with given fields: ctx, userID, email
func (_m *MockEmailVerifier) SendVerification(ctx context.Context, userID uuid.UUID, email string) error {
	ret := _m.Called(ctx, userID, email)

	if len(ret) == 0 {
		panic("no return value specified for SendVerification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, userID, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Verify provides a mock function with given fields: ctx, token
func (_m *MockEmailVerifier) Verify(ctx context.Context, token uuid.UUID) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockEmailVerifier creates a new instance of MockEmailVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmailVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmailVerifier {
	mock := &MockEmailVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
