// Code generated by mockery v2.53.6. DO NOT EDIT.

package service

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRegistrationService is an autogenerated mock type for the RegistrationService type
type MockRegistrationService struct {
	mock.Mock
}

// Register provides a mock function with given fields: ctx, email, password
func (_m *MockRegistrationService) Register(ctx context.Context, email string, password string) error {
	ret := _m.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, email, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockRegistrationService creates a new instance of MockRegistrationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRegistrationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRegistrationService {
	mock := &MockRegistrationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
